"""Verify source extraction without configuring or compiling OpenMS."""

from pathlib import Path
import json
import re
import unittest
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
GUI = ROOT / "gui"


class DesktopSourceBoundaries(unittest.TestCase):
    def test_resource_archive_is_complete(self):
        resource = GUI / "source/VISUAL/ICONS/resources.qrc"
        entries = list(ET.parse(resource).iter("file"))
        self.assertGreater(len(entries), 20)
        for entry in entries:
            with self.subTest(resource=entry.text):
                self.assertTrue((resource.parent / entry.text).is_file())

    def test_source_manifests_are_complete(self):
        listed_cpp = set()
        for manifest in GUI.rglob("sources.cmake"):
            text = "\n".join(line.split("#", 1)[0] for line in manifest.read_text().splitlines())
            directory = re.search(r"set\(directory\s+([^\s)]+)\)", text).group(1)
            for filename in re.findall(r"[A-Za-z0-9_/]+\.(?:cpp|h|ui)\b", text):
                path = GUI / directory / filename
                with self.subTest(manifest=str(manifest), source=filename):
                    self.assertTrue(path.is_file())
                if path.suffix == ".cpp":
                    listed_cpp.add(path)
        self.assertEqual(set(GUI.rglob("*.cpp")), listed_cpp)

    def test_visual_headers_resolve_within_gui_sdk(self):
        for source in list(GUI.rglob("*.cpp")) + list(GUI.rglob("*.h")):
            for include in re.findall(r"#\s*include\s*[<\"](OpenMS/VISUAL/[^>\"]+)[>\"]", source.read_text()):
                if include == "OpenMS/VISUAL/OpenMS_GUIConfig.h":
                    continue  # Generated by GenerateExportHeader.
                with self.subTest(source=str(source), include=include):
                    self.assertTrue((GUI / "include" / include).is_file())

    def test_ui_includes_have_inputs(self):
        forms = {path.stem for path in GUI.rglob("*.ui")}
        for source in list(GUI.rglob("*.cpp")) + list((ROOT / "tests/class_tests").rglob("*.h")):
            for form in re.findall(r"#\s*include\s*[<\"]ui_([^>\"]+)\.h[>\"]", source.read_text()):
                with self.subTest(source=str(source), form=form):
                    self.assertIn(form, forms)

    def test_frontends_have_single_owners(self):
        expected = {"viewers": {"TOPPView", "ImageCreator", "INIFileEditor"},
                    "workflows": {"TOPPAS", "ExecutePipeline"}}
        for package, names in expected.items():
            self.assertEqual({path.stem for path in (ROOT / package).glob("*.cpp")}, names)
        for name in expected["viewers"] | expected["workflows"]:
            self.assertFalse(list(GUI.rglob(name + ".cpp")))

    def test_native_application_resources(self):
        for package, names in {"viewers": ["TOPPView", "INIFileEditor"], "workflows": ["TOPPAS"]}.items():
            for name in names:
                directory = ROOT / package
                rc = (directory / (name + ".rc")).read_text()
                for icon in re.findall(r'ICON\s+"([^"]+)"', rc):
                    self.assertTrue((directory / icon).is_file())
                self.assertTrue((directory / (name + "-resources") / (name + ".icns")).is_file())
                ET.parse(directory / (name + "-resources") / (name + ".plist.in"))

    def test_pipeline_resource_inputs_are_owned(self):
        directory = ROOT / "tests/pipelines"
        text = (directory / "ExecutePipeline_1.trf.in").read_text()
        text = text.replace("${DATA_DIR_TOPPAS}", str(directory))
        for item in ET.fromstring(text).iter("LISTITEM"):
            self.assertTrue(Path(item.attrib["value"].removeprefix("file:")).is_file())

    def test_tool_discovery_has_no_sibling_layout_calls(self):
        for source in GUI.rglob("*.cpp"):
            self.assertNotIn("File::findSiblingTOPPExecutable", source.read_text(), str(source))
        helper = (GUI / "source/VISUAL/MISC/GUIHelpers.cpp").read_text()
        self.assertNotIn("../../../TOPPView.app", helper)

    def test_provenance_paths_exist(self):
        provenance = json.loads((ROOT / "source-provenance.json").read_text())
        for item in provenance["imported_files"]:
            with self.subTest(path=item["path"]):
                self.assertTrue((ROOT / item["path"]).is_file())


if __name__ == "__main__":
    unittest.main()
